name: venv
channels:
  - conda-forge
#  - defaults
#  - mathieu
#  - anaconda
dependencies:
  - python>=3.8
  - gcc
  - gxx
  - cxx-compiler
  - pdal
  - python-pdal
  - gdal
  - h5py
  - pyproj
  - xarray
  - sentinelhub
  - numpy
  - lxml
  - scipy
  - shapely
  - beautifulsoup4
  - mamba
  - pyyaml
  - requests
  - pip
  - pip:
    - git+https://github.com/QCDIS/multiply-core.git
    - git+https://github.com/QCDIS/data-access.git
    - git+https://github.com/QCDIS/inference-engine.git
    - git+https://github.com/QCDIS/KaFKA-InferenceEngine.git
    - git+https://github.com/QCDIS/multiply-orchestration
    - git+https://github.com/QCDIS/vm-support.git
    - git+https://github.com/QCDIS/prior-engine.git
    - git+https://github.com/QCDIS/BRDF_descriptors.git
    - git+https://github.com/JorisTimmermans/atmospheric_correction.git