name: venv
channels:
  - conda-forge
dependencies:
  - flake8
  - mamba
  - pyyaml
  - requests
  - pip
  - pip:
    - git+https://github.com/QCDIS/multiply-core.git
    - git+https://github.com/QCDIS/data-access.git
    - git+https://github.com/QCDIS/inference-engine.git
    - git+https://github.com/QCDIS/KaFKA-InferenceEngine.git
    - git+https://github.com/QCDIS/multiply-orchestration
    - git+https://github.com/QCDIS/vm-support.git
    - git+https://github.com/QCDIS/prior-engine.git
    - git+https://github.com/QCDIS/BRDF_descriptors.git
    - git+https://github.com/JorisTimmermans/atmospheric_correction.git